// Code generated by mockery v2.53.6. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "github.com/todo-app/backend/database"

	sql "database/sql"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CountGroupMembers provides a mock function with given fields: ctx, groupID
func (_m *MockQuerier) CountGroupMembers(ctx context.Context, groupID uint32) (int64, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for CountGroupMembers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (int64, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) int64); ok {
		r0 = rf(ctx, groupID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CountGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountGroupMembers'
type MockQuerier_CountGroupMembers_Call struct {
	*mock.Call
}

// CountGroupMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint32
func (_e *MockQuerier_Expecter) CountGroupMembers(ctx interface{}, groupID interface{}) *MockQuerier_CountGroupMembers_Call {
	return &MockQuerier_CountGroupMembers_Call{Call: _e.mock.On("CountGroupMembers", ctx, groupID)}
}

func (_c *MockQuerier_CountGroupMembers_Call) Run(run func(ctx context.Context, groupID uint32)) *MockQuerier_CountGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_CountGroupMembers_Call) Return(_a0 int64, _a1 error) *MockQuerier_CountGroupMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CountGroupMembers_Call) RunAndReturn(run func(context.Context, uint32) (int64, error)) *MockQuerier_CountGroupMembers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupShare provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateGroupShare(ctx context.Context, arg database.CreateGroupShareParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupShare")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateGroupShareParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateGroupShareParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateGroupShareParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateGroupShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupShare'
type MockQuerier_CreateGroupShare_Call struct {
	*mock.Call
}

// CreateGroupShare is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateGroupShareParams
func (_e *MockQuerier_Expecter) CreateGroupShare(ctx interface{}, arg interface{}) *MockQuerier_CreateGroupShare_Call {
	return &MockQuerier_CreateGroupShare_Call{Call: _e.mock.On("CreateGroupShare", ctx, arg)}
}

func (_c *MockQuerier_CreateGroupShare_Call) Run(run func(ctx context.Context, arg database.CreateGroupShareParams)) *MockQuerier_CreateGroupShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateGroupShareParams))
	})
	return _c
}

func (_c *MockQuerier_CreateGroupShare_Call) Return(_a0 sql.Result, _a1 error) *MockQuerier_CreateGroupShare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateGroupShare_Call) RunAndReturn(run func(context.Context, database.CreateGroupShareParams) (sql.Result, error)) *MockQuerier_CreateGroupShare_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTodo provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateTodo(ctx context.Context, arg database.CreateTodoParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateTodoParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateTodoParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateTodoParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockQuerier_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateTodoParams
func (_e *MockQuerier_Expecter) CreateTodo(ctx interface{}, arg interface{}) *MockQuerier_CreateTodo_Call {
	return &MockQuerier_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, arg)}
}

func (_c *MockQuerier_CreateTodo_Call) Run(run func(ctx context.Context, arg database.CreateTodoParams)) *MockQuerier_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateTodoParams))
	})
	return _c
}

func (_c *MockQuerier_CreateTodo_Call) Return(_a0 sql.Result, _a1 error) *MockQuerier_CreateTodo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateTodo_Call) RunAndReturn(run func(context.Context, database.CreateTodoParams) (sql.Result, error)) *MockQuerier_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUser(ctx context.Context, arg database.CreateUserParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg database.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateUserParams))
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(_a0 sql.Result, _a1 error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(context.Context, database.CreateUserParams) (sql.Result, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroupShare provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteGroupShare(ctx context.Context, arg database.DeleteGroupShareParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroupShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.DeleteGroupShareParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteGroupShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroupShare'
type MockQuerier_DeleteGroupShare_Call struct {
	*mock.Call
}

// DeleteGroupShare is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.DeleteGroupShareParams
func (_e *MockQuerier_Expecter) DeleteGroupShare(ctx interface{}, arg interface{}) *MockQuerier_DeleteGroupShare_Call {
	return &MockQuerier_DeleteGroupShare_Call{Call: _e.mock.On("DeleteGroupShare", ctx, arg)}
}

func (_c *MockQuerier_DeleteGroupShare_Call) Run(run func(ctx context.Context, arg database.DeleteGroupShareParams)) *MockQuerier_DeleteGroupShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.DeleteGroupShareParams))
	})
	return _c
}

func (_c *MockQuerier_DeleteGroupShare_Call) Return(_a0 error) *MockQuerier_DeleteGroupShare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteGroupShare_Call) RunAndReturn(run func(context.Context, database.DeleteGroupShareParams) error) *MockQuerier_DeleteGroupShare_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteTodo(ctx context.Context, id uint32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockQuerier_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockQuerier_Expecter) DeleteTodo(ctx interface{}, id interface{}) *MockQuerier_DeleteTodo_Call {
	return &MockQuerier_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, id)}
}

func (_c *MockQuerier_DeleteTodo_Call) Run(run func(ctx context.Context, id uint32)) *MockQuerier_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_DeleteTodo_Call) Return(_a0 error) *MockQuerier_DeleteTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteTodo_Call) RunAndReturn(run func(context.Context, uint32) error) *MockQuerier_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetGroupByID(ctx context.Context, id uint32) (database.Todo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByID")
	}

	var r0 database.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (database.Todo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) database.Todo); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Todo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByID'
type MockQuerier_GetGroupByID_Call struct {
	*mock.Call
}

// GetGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockQuerier_Expecter) GetGroupByID(ctx interface{}, id interface{}) *MockQuerier_GetGroupByID_Call {
	return &MockQuerier_GetGroupByID_Call{Call: _e.mock.On("GetGroupByID", ctx, id)}
}

func (_c *MockQuerier_GetGroupByID_Call) Run(run func(ctx context.Context, id uint32)) *MockQuerier_GetGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_GetGroupByID_Call) Return(_a0 database.Todo, _a1 error) *MockQuerier_GetGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetGroupByID_Call) RunAndReturn(run func(context.Context, uint32) (database.Todo, error)) *MockQuerier_GetGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupShare provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetGroupShare(ctx context.Context, arg database.GetGroupShareParams) (database.GroupShare, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupShare")
	}

	var r0 database.GroupShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetGroupShareParams) (database.GroupShare, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetGroupShareParams) database.GroupShare); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.GroupShare)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetGroupShareParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetGroupShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupShare'
type MockQuerier_GetGroupShare_Call struct {
	*mock.Call
}

// GetGroupShare is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetGroupShareParams
func (_e *MockQuerier_Expecter) GetGroupShare(ctx interface{}, arg interface{}) *MockQuerier_GetGroupShare_Call {
	return &MockQuerier_GetGroupShare_Call{Call: _e.mock.On("GetGroupShare", ctx, arg)}
}

func (_c *MockQuerier_GetGroupShare_Call) Run(run func(ctx context.Context, arg database.GetGroupShareParams)) *MockQuerier_GetGroupShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetGroupShareParams))
	})
	return _c
}

func (_c *MockQuerier_GetGroupShare_Call) Return(_a0 database.GroupShare, _a1 error) *MockQuerier_GetGroupShare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetGroupShare_Call) RunAndReturn(run func(context.Context, database.GetGroupShareParams) (database.GroupShare, error)) *MockQuerier_GetGroupShare_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupSharesByGroupID provides a mock function with given fields: ctx, groupID
func (_m *MockQuerier) GetGroupSharesByGroupID(ctx context.Context, groupID uint32) ([]database.GetGroupSharesByGroupIDRow, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupSharesByGroupID")
	}

	var r0 []database.GetGroupSharesByGroupIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) ([]database.GetGroupSharesByGroupIDRow, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) []database.GetGroupSharesByGroupIDRow); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetGroupSharesByGroupIDRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetGroupSharesByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupSharesByGroupID'
type MockQuerier_GetGroupSharesByGroupID_Call struct {
	*mock.Call
}

// GetGroupSharesByGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint32
func (_e *MockQuerier_Expecter) GetGroupSharesByGroupID(ctx interface{}, groupID interface{}) *MockQuerier_GetGroupSharesByGroupID_Call {
	return &MockQuerier_GetGroupSharesByGroupID_Call{Call: _e.mock.On("GetGroupSharesByGroupID", ctx, groupID)}
}

func (_c *MockQuerier_GetGroupSharesByGroupID_Call) Run(run func(ctx context.Context, groupID uint32)) *MockQuerier_GetGroupSharesByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_GetGroupSharesByGroupID_Call) Return(_a0 []database.GetGroupSharesByGroupIDRow, _a1 error) *MockQuerier_GetGroupSharesByGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetGroupSharesByGroupID_Call) RunAndReturn(run func(context.Context, uint32) ([]database.GetGroupSharesByGroupIDRow, error)) *MockQuerier_GetGroupSharesByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupsByUserID provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetGroupsByUserID(ctx context.Context, arg database.GetGroupsByUserIDParams) ([]database.Todo, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupsByUserID")
	}

	var r0 []database.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetGroupsByUserIDParams) ([]database.Todo, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetGroupsByUserIDParams) []database.Todo); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetGroupsByUserIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetGroupsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupsByUserID'
type MockQuerier_GetGroupsByUserID_Call struct {
	*mock.Call
}

// GetGroupsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetGroupsByUserIDParams
func (_e *MockQuerier_Expecter) GetGroupsByUserID(ctx interface{}, arg interface{}) *MockQuerier_GetGroupsByUserID_Call {
	return &MockQuerier_GetGroupsByUserID_Call{Call: _e.mock.On("GetGroupsByUserID", ctx, arg)}
}

func (_c *MockQuerier_GetGroupsByUserID_Call) Run(run func(ctx context.Context, arg database.GetGroupsByUserIDParams)) *MockQuerier_GetGroupsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetGroupsByUserIDParams))
	})
	return _c
}

func (_c *MockQuerier_GetGroupsByUserID_Call) Return(_a0 []database.Todo, _a1 error) *MockQuerier_GetGroupsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetGroupsByUserID_Call) RunAndReturn(run func(context.Context, database.GetGroupsByUserIDParams) ([]database.Todo, error)) *MockQuerier_GetGroupsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharesByUserID provides a mock function with given fields: ctx, sharedWithUserID
func (_m *MockQuerier) GetSharesByUserID(ctx context.Context, sharedWithUserID uint32) ([]database.GetSharesByUserIDRow, error) {
	ret := _m.Called(ctx, sharedWithUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetSharesByUserID")
	}

	var r0 []database.GetSharesByUserIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) ([]database.GetSharesByUserIDRow, error)); ok {
		return rf(ctx, sharedWithUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) []database.GetSharesByUserIDRow); ok {
		r0 = rf(ctx, sharedWithUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetSharesByUserIDRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, sharedWithUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetSharesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharesByUserID'
type MockQuerier_GetSharesByUserID_Call struct {
	*mock.Call
}

// GetSharesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - sharedWithUserID uint32
func (_e *MockQuerier_Expecter) GetSharesByUserID(ctx interface{}, sharedWithUserID interface{}) *MockQuerier_GetSharesByUserID_Call {
	return &MockQuerier_GetSharesByUserID_Call{Call: _e.mock.On("GetSharesByUserID", ctx, sharedWithUserID)}
}

func (_c *MockQuerier_GetSharesByUserID_Call) Run(run func(ctx context.Context, sharedWithUserID uint32)) *MockQuerier_GetSharesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_GetSharesByUserID_Call) Return(_a0 []database.GetSharesByUserIDRow, _a1 error) *MockQuerier_GetSharesByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetSharesByUserID_Call) RunAndReturn(run func(context.Context, uint32) ([]database.GetSharesByUserIDRow, error)) *MockQuerier_GetSharesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtasksByParentAndUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetSubtasksByParentAndUser(ctx context.Context, arg database.GetSubtasksByParentAndUserParams) ([]database.Todo, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtasksByParentAndUser")
	}

	var r0 []database.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetSubtasksByParentAndUserParams) ([]database.Todo, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetSubtasksByParentAndUserParams) []database.Todo); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetSubtasksByParentAndUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetSubtasksByParentAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtasksByParentAndUser'
type MockQuerier_GetSubtasksByParentAndUser_Call struct {
	*mock.Call
}

// GetSubtasksByParentAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetSubtasksByParentAndUserParams
func (_e *MockQuerier_Expecter) GetSubtasksByParentAndUser(ctx interface{}, arg interface{}) *MockQuerier_GetSubtasksByParentAndUser_Call {
	return &MockQuerier_GetSubtasksByParentAndUser_Call{Call: _e.mock.On("GetSubtasksByParentAndUser", ctx, arg)}
}

func (_c *MockQuerier_GetSubtasksByParentAndUser_Call) Run(run func(ctx context.Context, arg database.GetSubtasksByParentAndUserParams)) *MockQuerier_GetSubtasksByParentAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetSubtasksByParentAndUserParams))
	})
	return _c
}

func (_c *MockQuerier_GetSubtasksByParentAndUser_Call) Return(_a0 []database.Todo, _a1 error) *MockQuerier_GetSubtasksByParentAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetSubtasksByParentAndUser_Call) RunAndReturn(run func(context.Context, database.GetSubtasksByParentAndUserParams) ([]database.Todo, error)) *MockQuerier_GetSubtasksByParentAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtasksByParentID provides a mock function with given fields: ctx, parentTodoID
func (_m *MockQuerier) GetSubtasksByParentID(ctx context.Context, parentTodoID sql.NullInt32) ([]database.Todo, error) {
	ret := _m.Called(ctx, parentTodoID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtasksByParentID")
	}

	var r0 []database.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt32) ([]database.Todo, error)); ok {
		return rf(ctx, parentTodoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt32) []database.Todo); ok {
		r0 = rf(ctx, parentTodoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql.NullInt32) error); ok {
		r1 = rf(ctx, parentTodoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetSubtasksByParentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtasksByParentID'
type MockQuerier_GetSubtasksByParentID_Call struct {
	*mock.Call
}

// GetSubtasksByParentID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentTodoID sql.NullInt32
func (_e *MockQuerier_Expecter) GetSubtasksByParentID(ctx interface{}, parentTodoID interface{}) *MockQuerier_GetSubtasksByParentID_Call {
	return &MockQuerier_GetSubtasksByParentID_Call{Call: _e.mock.On("GetSubtasksByParentID", ctx, parentTodoID)}
}

func (_c *MockQuerier_GetSubtasksByParentID_Call) Run(run func(ctx context.Context, parentTodoID sql.NullInt32)) *MockQuerier_GetSubtasksByParentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql.NullInt32))
	})
	return _c
}

func (_c *MockQuerier_GetSubtasksByParentID_Call) Return(_a0 []database.Todo, _a1 error) *MockQuerier_GetSubtasksByParentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetSubtasksByParentID_Call) RunAndReturn(run func(context.Context, sql.NullInt32) ([]database.Todo, error)) *MockQuerier_GetSubtasksByParentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodoByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetTodoByID(ctx context.Context, id uint32) (database.Todo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodoByID")
	}

	var r0 database.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (database.Todo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) database.Todo); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Todo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetTodoByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodoByID'
type MockQuerier_GetTodoByID_Call struct {
	*mock.Call
}

// GetTodoByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockQuerier_Expecter) GetTodoByID(ctx interface{}, id interface{}) *MockQuerier_GetTodoByID_Call {
	return &MockQuerier_GetTodoByID_Call{Call: _e.mock.On("GetTodoByID", ctx, id)}
}

func (_c *MockQuerier_GetTodoByID_Call) Run(run func(ctx context.Context, id uint32)) *MockQuerier_GetTodoByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_GetTodoByID_Call) Return(_a0 database.Todo, _a1 error) *MockQuerier_GetTodoByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetTodoByID_Call) RunAndReturn(run func(context.Context, uint32) (database.Todo, error)) *MockQuerier_GetTodoByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (database.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockQuerier_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerier_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockQuerier_GetUserByEmail_Call {
	return &MockQuerier_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockQuerier_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) Return(_a0 database.User, _a1 error) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (database.User, error)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetUserByID(ctx context.Context, id uint32) (database.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (database.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) database.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockQuerier_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockQuerier_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockQuerier_GetUserByID_Call {
	return &MockQuerier_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockQuerier_GetUserByID_Call) Run(run func(ctx context.Context, id uint32)) *MockQuerier_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockQuerier_GetUserByID_Call) Return(_a0 database.User, _a1 error) *MockQuerier_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetUserByID_Call) RunAndReturn(run func(context.Context, uint32) (database.User, error)) *MockQuerier_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SearchUsers(ctx context.Context, arg database.SearchUsersParams) ([]database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.SearchUsersParams) ([]database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.SearchUsersParams) []database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.SearchUsersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockQuerier_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.SearchUsersParams
func (_e *MockQuerier_Expecter) SearchUsers(ctx interface{}, arg interface{}) *MockQuerier_SearchUsers_Call {
	return &MockQuerier_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, arg)}
}

func (_c *MockQuerier_SearchUsers_Call) Run(run func(ctx context.Context, arg database.SearchUsersParams)) *MockQuerier_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.SearchUsersParams))
	})
	return _c
}

func (_c *MockQuerier_SearchUsers_Call) Return(_a0 []database.User, _a1 error) *MockQuerier_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_SearchUsers_Call) RunAndReturn(run func(context.Context, database.SearchUsersParams) ([]database.User, error)) *MockQuerier_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroupSharePermission provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateGroupSharePermission(ctx context.Context, arg database.UpdateGroupSharePermissionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroupSharePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateGroupSharePermissionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_UpdateGroupSharePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroupSharePermission'
type MockQuerier_UpdateGroupSharePermission_Call struct {
	*mock.Call
}

// UpdateGroupSharePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateGroupSharePermissionParams
func (_e *MockQuerier_Expecter) UpdateGroupSharePermission(ctx interface{}, arg interface{}) *MockQuerier_UpdateGroupSharePermission_Call {
	return &MockQuerier_UpdateGroupSharePermission_Call{Call: _e.mock.On("UpdateGroupSharePermission", ctx, arg)}
}

func (_c *MockQuerier_UpdateGroupSharePermission_Call) Run(run func(ctx context.Context, arg database.UpdateGroupSharePermissionParams)) *MockQuerier_UpdateGroupSharePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateGroupSharePermissionParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateGroupSharePermission_Call) Return(_a0 error) *MockQuerier_UpdateGroupSharePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_UpdateGroupSharePermission_Call) RunAndReturn(run func(context.Context, database.UpdateGroupSharePermissionParams) error) *MockQuerier_UpdateGroupSharePermission_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateTodo(ctx context.Context, arg database.UpdateTodoParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateTodoParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockQuerier_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateTodoParams
func (_e *MockQuerier_Expecter) UpdateTodo(ctx interface{}, arg interface{}) *MockQuerier_UpdateTodo_Call {
	return &MockQuerier_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, arg)}
}

func (_c *MockQuerier_UpdateTodo_Call) Run(run func(ctx context.Context, arg database.UpdateTodoParams)) *MockQuerier_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateTodoParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateTodo_Call) Return(_a0 error) *MockQuerier_UpdateTodo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_UpdateTodo_Call) RunAndReturn(run func(context.Context, database.UpdateTodoParams) error) *MockQuerier_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUserPassword(ctx context.Context, arg database.UpdateUserPasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserPasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockQuerier_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateUserPasswordParams
func (_e *MockQuerier_Expecter) UpdateUserPassword(ctx interface{}, arg interface{}) *MockQuerier_UpdateUserPassword_Call {
	return &MockQuerier_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, arg)}
}

func (_c *MockQuerier_UpdateUserPassword_Call) Run(run func(ctx context.Context, arg database.UpdateUserPasswordParams)) *MockQuerier_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateUserPasswordParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateUserPassword_Call) Return(_a0 error) *MockQuerier_UpdateUserPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_UpdateUserPassword_Call) RunAndReturn(run func(context.Context, database.UpdateUserPasswordParams) error) *MockQuerier_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
