// Code generated by mockery v2.53.6. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/todo-app/backend/models"
)

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, todo
func (_m *MockTodoRepository) Create(ctx context.Context, todo *models.Todo) error {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Todo) error); ok {
		r0 = rf(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTodoRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *models.Todo
func (_e *MockTodoRepository_Expecter) Create(ctx interface{}, todo interface{}) *MockTodoRepository_Create_Call {
	return &MockTodoRepository_Create_Call{Call: _e.mock.On("Create", ctx, todo)}
}

func (_c *MockTodoRepository_Create_Call) Run(run func(ctx context.Context, todo *models.Todo)) *MockTodoRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Todo))
	})
	return _c
}

func (_c *MockTodoRepository_Create_Call) Return(_a0 error) *MockTodoRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Todo) error) *MockTodoRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTodoRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTodoRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTodoRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTodoRepository_Delete_Call {
	return &MockTodoRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTodoRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockTodoRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockTodoRepository_Delete_Call) Return(_a0 error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllGroupsByUserID provides a mock function with given fields: ctx, userID, search, status, sortParam
func (_m *MockTodoRepository) FindAllGroupsByUserID(ctx context.Context, userID uint, search string, status string, sortParam string) ([]models.Todo, error) {
	ret := _m.Called(ctx, userID, search, status, sortParam)

	if len(ret) == 0 {
		panic("no return value specified for FindAllGroupsByUserID")
	}

	var r0 []models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string) ([]models.Todo, error)); ok {
		return rf(ctx, userID, search, status, sortParam)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string) []models.Todo); ok {
		r0 = rf(ctx, userID, search, status, sortParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, string, string) error); ok {
		r1 = rf(ctx, userID, search, status, sortParam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_FindAllGroupsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllGroupsByUserID'
type MockTodoRepository_FindAllGroupsByUserID_Call struct {
	*mock.Call
}

// FindAllGroupsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - search string
//   - status string
//   - sortParam string
func (_e *MockTodoRepository_Expecter) FindAllGroupsByUserID(ctx interface{}, userID interface{}, search interface{}, status interface{}, sortParam interface{}) *MockTodoRepository_FindAllGroupsByUserID_Call {
	return &MockTodoRepository_FindAllGroupsByUserID_Call{Call: _e.mock.On("FindAllGroupsByUserID", ctx, userID, search, status, sortParam)}
}

func (_c *MockTodoRepository_FindAllGroupsByUserID_Call) Run(run func(ctx context.Context, userID uint, search string, status string, sortParam string)) *MockTodoRepository_FindAllGroupsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockTodoRepository_FindAllGroupsByUserID_Call) Return(_a0 []models.Todo, _a1 error) *MockTodoRepository_FindAllGroupsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_FindAllGroupsByUserID_Call) RunAndReturn(run func(context.Context, uint, string, string, string) ([]models.Todo, error)) *MockTodoRepository_FindAllGroupsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTodoRepository) FindByID(ctx context.Context, id uint) (*models.Todo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Todo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Todo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTodoRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTodoRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTodoRepository_FindByID_Call {
	return &MockTodoRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTodoRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockTodoRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockTodoRepository_FindByID_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Todo, error)) *MockTodoRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindGroupByID provides a mock function with given fields: ctx, id, userID
func (_m *MockTodoRepository) FindGroupByID(ctx context.Context, id uint, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindGroupByID")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*models.Todo, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *models.Todo); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_FindGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGroupByID'
type MockTodoRepository_FindGroupByID_Call struct {
	*mock.Call
}

// FindGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - userID uint
func (_e *MockTodoRepository_Expecter) FindGroupByID(ctx interface{}, id interface{}, userID interface{}) *MockTodoRepository_FindGroupByID_Call {
	return &MockTodoRepository_FindGroupByID_Call{Call: _e.mock.On("FindGroupByID", ctx, id, userID)}
}

func (_c *MockTodoRepository_FindGroupByID_Call) Run(run func(ctx context.Context, id uint, userID uint)) *MockTodoRepository_FindGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoRepository_FindGroupByID_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoRepository_FindGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_FindGroupByID_Call) RunAndReturn(run func(context.Context, uint, uint) (*models.Todo, error)) *MockTodoRepository_FindGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSubtasksByGroupID provides a mock function with given fields: ctx, groupID, userID
func (_m *MockTodoRepository) FindSubtasksByGroupID(ctx context.Context, groupID uint, userID uint) ([]models.Todo, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindSubtasksByGroupID")
	}

	var r0 []models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) ([]models.Todo, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []models.Todo); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoRepository_FindSubtasksByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSubtasksByGroupID'
type MockTodoRepository_FindSubtasksByGroupID_Call struct {
	*mock.Call
}

// FindSubtasksByGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - userID uint
func (_e *MockTodoRepository_Expecter) FindSubtasksByGroupID(ctx interface{}, groupID interface{}, userID interface{}) *MockTodoRepository_FindSubtasksByGroupID_Call {
	return &MockTodoRepository_FindSubtasksByGroupID_Call{Call: _e.mock.On("FindSubtasksByGroupID", ctx, groupID, userID)}
}

func (_c *MockTodoRepository_FindSubtasksByGroupID_Call) Run(run func(ctx context.Context, groupID uint, userID uint)) *MockTodoRepository_FindSubtasksByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoRepository_FindSubtasksByGroupID_Call) Return(_a0 []models.Todo, _a1 error) *MockTodoRepository_FindSubtasksByGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoRepository_FindSubtasksByGroupID_Call) RunAndReturn(run func(context.Context, uint, uint) ([]models.Todo, error)) *MockTodoRepository_FindSubtasksByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, todo
func (_m *MockTodoRepository) Update(ctx context.Context, todo *models.Todo) error {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Todo) error); ok {
		r0 = rf(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTodoRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *models.Todo
func (_e *MockTodoRepository_Expecter) Update(ctx interface{}, todo interface{}) *MockTodoRepository_Update_Call {
	return &MockTodoRepository_Update_Call{Call: _e.mock.On("Update", ctx, todo)}
}

func (_c *MockTodoRepository_Update_Call) Run(run func(ctx context.Context, todo *models.Todo)) *MockTodoRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Todo))
	})
	return _c
}

func (_c *MockTodoRepository_Update_Call) Return(_a0 error) *MockTodoRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Todo) error) *MockTodoRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
