// Code generated by mockery v2.53.6. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/todo-app/backend/models"
)

// MockGroupShareRepository is an autogenerated mock type for the GroupShareRepository type
type MockGroupShareRepository struct {
	mock.Mock
}

type MockGroupShareRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupShareRepository) EXPECT() *MockGroupShareRepository_Expecter {
	return &MockGroupShareRepository_Expecter{mock: &_m.Mock}
}

// CountMembersByGroupID provides a mock function with given fields: ctx, groupID
func (_m *MockGroupShareRepository) CountMembersByGroupID(ctx context.Context, groupID uint) (int, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for CountMembersByGroupID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, groupID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupShareRepository_CountMembersByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMembersByGroupID'
type MockGroupShareRepository_CountMembersByGroupID_Call struct {
	*mock.Call
}

// CountMembersByGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
func (_e *MockGroupShareRepository_Expecter) CountMembersByGroupID(ctx interface{}, groupID interface{}) *MockGroupShareRepository_CountMembersByGroupID_Call {
	return &MockGroupShareRepository_CountMembersByGroupID_Call{Call: _e.mock.On("CountMembersByGroupID", ctx, groupID)}
}

func (_c *MockGroupShareRepository_CountMembersByGroupID_Call) Run(run func(ctx context.Context, groupID uint)) *MockGroupShareRepository_CountMembersByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockGroupShareRepository_CountMembersByGroupID_Call) Return(_a0 int, _a1 error) *MockGroupShareRepository_CountMembersByGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupShareRepository_CountMembersByGroupID_Call) RunAndReturn(run func(context.Context, uint) (int, error)) *MockGroupShareRepository_CountMembersByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, share
func (_m *MockGroupShareRepository) Create(ctx context.Context, share *models.GroupShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GroupShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupShareRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupShareRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - share *models.GroupShare
func (_e *MockGroupShareRepository_Expecter) Create(ctx interface{}, share interface{}) *MockGroupShareRepository_Create_Call {
	return &MockGroupShareRepository_Create_Call{Call: _e.mock.On("Create", ctx, share)}
}

func (_c *MockGroupShareRepository_Create_Call) Run(run func(ctx context.Context, share *models.GroupShare)) *MockGroupShareRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GroupShare))
	})
	return _c
}

func (_c *MockGroupShareRepository_Create_Call) Return(_a0 error) *MockGroupShareRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupShareRepository_Create_Call) RunAndReturn(run func(context.Context, *models.GroupShare) error) *MockGroupShareRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, groupID, userID
func (_m *MockGroupShareRepository) Delete(ctx context.Context, groupID uint, userID uint) error {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupShareRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupShareRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - userID uint
func (_e *MockGroupShareRepository_Expecter) Delete(ctx interface{}, groupID interface{}, userID interface{}) *MockGroupShareRepository_Delete_Call {
	return &MockGroupShareRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, groupID, userID)}
}

func (_c *MockGroupShareRepository_Delete_Call) Run(run func(ctx context.Context, groupID uint, userID uint)) *MockGroupShareRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockGroupShareRepository_Delete_Call) Return(_a0 error) *MockGroupShareRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupShareRepository_Delete_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockGroupShareRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindMembersByGroupID provides a mock function with given fields: ctx, groupID
func (_m *MockGroupShareRepository) FindMembersByGroupID(ctx context.Context, groupID uint) ([]models.GroupShare, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindMembersByGroupID")
	}

	var r0 []models.GroupShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]models.GroupShare, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []models.GroupShare); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupShareRepository_FindMembersByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMembersByGroupID'
type MockGroupShareRepository_FindMembersByGroupID_Call struct {
	*mock.Call
}

// FindMembersByGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
func (_e *MockGroupShareRepository_Expecter) FindMembersByGroupID(ctx interface{}, groupID interface{}) *MockGroupShareRepository_FindMembersByGroupID_Call {
	return &MockGroupShareRepository_FindMembersByGroupID_Call{Call: _e.mock.On("FindMembersByGroupID", ctx, groupID)}
}

func (_c *MockGroupShareRepository_FindMembersByGroupID_Call) Run(run func(ctx context.Context, groupID uint)) *MockGroupShareRepository_FindMembersByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockGroupShareRepository_FindMembersByGroupID_Call) Return(_a0 []models.GroupShare, _a1 error) *MockGroupShareRepository_FindMembersByGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupShareRepository_FindMembersByGroupID_Call) RunAndReturn(run func(context.Context, uint) ([]models.GroupShare, error)) *MockGroupShareRepository_FindMembersByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// FindShare provides a mock function with given fields: ctx, groupID, sharedWithUserID
func (_m *MockGroupShareRepository) FindShare(ctx context.Context, groupID uint, sharedWithUserID uint) (*models.GroupShare, error) {
	ret := _m.Called(ctx, groupID, sharedWithUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindShare")
	}

	var r0 *models.GroupShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*models.GroupShare, error)); ok {
		return rf(ctx, groupID, sharedWithUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *models.GroupShare); ok {
		r0 = rf(ctx, groupID, sharedWithUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GroupShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, groupID, sharedWithUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupShareRepository_FindShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindShare'
type MockGroupShareRepository_FindShare_Call struct {
	*mock.Call
}

// FindShare is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - sharedWithUserID uint
func (_e *MockGroupShareRepository_Expecter) FindShare(ctx interface{}, groupID interface{}, sharedWithUserID interface{}) *MockGroupShareRepository_FindShare_Call {
	return &MockGroupShareRepository_FindShare_Call{Call: _e.mock.On("FindShare", ctx, groupID, sharedWithUserID)}
}

func (_c *MockGroupShareRepository_FindShare_Call) Run(run func(ctx context.Context, groupID uint, sharedWithUserID uint)) *MockGroupShareRepository_FindShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockGroupShareRepository_FindShare_Call) Return(_a0 *models.GroupShare, _a1 error) *MockGroupShareRepository_FindShare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupShareRepository_FindShare_Call) RunAndReturn(run func(context.Context, uint, uint) (*models.GroupShare, error)) *MockGroupShareRepository_FindShare_Call {
	_c.Call.Return(run)
	return _c
}

// FindSharedGroupsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockGroupShareRepository) FindSharedGroupsByUserID(ctx context.Context, userID uint) ([]models.GroupShare, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindSharedGroupsByUserID")
	}

	var r0 []models.GroupShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]models.GroupShare, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []models.GroupShare); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupShareRepository_FindSharedGroupsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSharedGroupsByUserID'
type MockGroupShareRepository_FindSharedGroupsByUserID_Call struct {
	*mock.Call
}

// FindSharedGroupsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockGroupShareRepository_Expecter) FindSharedGroupsByUserID(ctx interface{}, userID interface{}) *MockGroupShareRepository_FindSharedGroupsByUserID_Call {
	return &MockGroupShareRepository_FindSharedGroupsByUserID_Call{Call: _e.mock.On("FindSharedGroupsByUserID", ctx, userID)}
}

func (_c *MockGroupShareRepository_FindSharedGroupsByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockGroupShareRepository_FindSharedGroupsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockGroupShareRepository_FindSharedGroupsByUserID_Call) Return(_a0 []models.GroupShare, _a1 error) *MockGroupShareRepository_FindSharedGroupsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupShareRepository_FindSharedGroupsByUserID_Call) RunAndReturn(run func(context.Context, uint) ([]models.GroupShare, error)) *MockGroupShareRepository_FindSharedGroupsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function with given fields: ctx, groupID, sharedWithUserID, permission
func (_m *MockGroupShareRepository) UpdatePermission(ctx context.Context, groupID uint, sharedWithUserID uint, permission string) error {
	ret := _m.Called(ctx, groupID, sharedWithUserID, permission)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) error); ok {
		r0 = rf(ctx, groupID, sharedWithUserID, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupShareRepository_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockGroupShareRepository_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - sharedWithUserID uint
//   - permission string
func (_e *MockGroupShareRepository_Expecter) UpdatePermission(ctx interface{}, groupID interface{}, sharedWithUserID interface{}, permission interface{}) *MockGroupShareRepository_UpdatePermission_Call {
	return &MockGroupShareRepository_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, groupID, sharedWithUserID, permission)}
}

func (_c *MockGroupShareRepository_UpdatePermission_Call) Run(run func(ctx context.Context, groupID uint, sharedWithUserID uint, permission string)) *MockGroupShareRepository_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(string))
	})
	return _c
}

func (_c *MockGroupShareRepository_UpdatePermission_Call) Return(_a0 error) *MockGroupShareRepository_UpdatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupShareRepository_UpdatePermission_Call) RunAndReturn(run func(context.Context, uint, uint, string) error) *MockGroupShareRepository_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupShareRepository creates a new instance of MockGroupShareRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupShareRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupShareRepository {
	mock := &MockGroupShareRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
