// Code generated by mockery v2.53.6. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/todo-app/backend/controllers/dto"

	models "github.com/todo-app/backend/models"
)

// MockTodoService is an autogenerated mock type for the TodoService type
type MockTodoService struct {
	mock.Mock
}

type MockTodoService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoService) EXPECT() *MockTodoService_Expecter {
	return &MockTodoService_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function with given fields: ctx, req, userID
func (_m *MockTodoService) CreateGroup(ctx context.Context, req dto.CreateGroupRequest, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateGroupRequest, uint) (*models.Todo, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateGroupRequest, uint) *models.Todo); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateGroupRequest, uint) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockTodoService_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateGroupRequest
//   - userID uint
func (_e *MockTodoService_Expecter) CreateGroup(ctx interface{}, req interface{}, userID interface{}) *MockTodoService_CreateGroup_Call {
	return &MockTodoService_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, req, userID)}
}

func (_c *MockTodoService_CreateGroup_Call) Run(run func(ctx context.Context, req dto.CreateGroupRequest, userID uint)) *MockTodoService_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateGroupRequest), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_CreateGroup_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoService_CreateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_CreateGroup_Call) RunAndReturn(run func(context.Context, dto.CreateGroupRequest, uint) (*models.Todo, error)) *MockTodoService_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubtask provides a mock function with given fields: ctx, req, userID
func (_m *MockTodoService) CreateSubtask(ctx context.Context, req dto.CreateSubtaskRequest, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubtask")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateSubtaskRequest, uint) (*models.Todo, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateSubtaskRequest, uint) *models.Todo); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateSubtaskRequest, uint) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_CreateSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubtask'
type MockTodoService_CreateSubtask_Call struct {
	*mock.Call
}

// CreateSubtask is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateSubtaskRequest
//   - userID uint
func (_e *MockTodoService_Expecter) CreateSubtask(ctx interface{}, req interface{}, userID interface{}) *MockTodoService_CreateSubtask_Call {
	return &MockTodoService_CreateSubtask_Call{Call: _e.mock.On("CreateSubtask", ctx, req, userID)}
}

func (_c *MockTodoService_CreateSubtask_Call) Run(run func(ctx context.Context, req dto.CreateSubtaskRequest, userID uint)) *MockTodoService_CreateSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateSubtaskRequest), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_CreateSubtask_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoService_CreateSubtask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_CreateSubtask_Call) RunAndReturn(run func(context.Context, dto.CreateSubtaskRequest, uint) (*models.Todo, error)) *MockTodoService_CreateSubtask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function with given fields: ctx, id, userID
func (_m *MockTodoService) DeleteGroup(ctx context.Context, id uint, userID uint) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoService_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockTodoService_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - userID uint
func (_e *MockTodoService_Expecter) DeleteGroup(ctx interface{}, id interface{}, userID interface{}) *MockTodoService_DeleteGroup_Call {
	return &MockTodoService_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, id, userID)}
}

func (_c *MockTodoService_DeleteGroup_Call) Run(run func(ctx context.Context, id uint, userID uint)) *MockTodoService_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_DeleteGroup_Call) Return(_a0 error) *MockTodoService_DeleteGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoService_DeleteGroup_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockTodoService_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubtask provides a mock function with given fields: ctx, id, userID
func (_m *MockTodoService) DeleteSubtask(ctx context.Context, id uint, userID uint) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubtask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoService_DeleteSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubtask'
type MockTodoService_DeleteSubtask_Call struct {
	*mock.Call
}

// DeleteSubtask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - userID uint
func (_e *MockTodoService_Expecter) DeleteSubtask(ctx interface{}, id interface{}, userID interface{}) *MockTodoService_DeleteSubtask_Call {
	return &MockTodoService_DeleteSubtask_Call{Call: _e.mock.On("DeleteSubtask", ctx, id, userID)}
}

func (_c *MockTodoService_DeleteSubtask_Call) Run(run func(ctx context.Context, id uint, userID uint)) *MockTodoService_DeleteSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_DeleteSubtask_Call) Return(_a0 error) *MockTodoService_DeleteSubtask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoService_DeleteSubtask_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockTodoService_DeleteSubtask_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupByID provides a mock function with given fields: ctx, id, userID
func (_m *MockTodoService) GetGroupByID(ctx context.Context, id uint, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByID")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*models.Todo, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *models.Todo); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_GetGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByID'
type MockTodoService_GetGroupByID_Call struct {
	*mock.Call
}

// GetGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - userID uint
func (_e *MockTodoService_Expecter) GetGroupByID(ctx interface{}, id interface{}, userID interface{}) *MockTodoService_GetGroupByID_Call {
	return &MockTodoService_GetGroupByID_Call{Call: _e.mock.On("GetGroupByID", ctx, id, userID)}
}

func (_c *MockTodoService_GetGroupByID_Call) Run(run func(ctx context.Context, id uint, userID uint)) *MockTodoService_GetGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_GetGroupByID_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoService_GetGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_GetGroupByID_Call) RunAndReturn(run func(context.Context, uint, uint) (*models.Todo, error)) *MockTodoService_GetGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupMembers provides a mock function with given fields: ctx, groupID, requesterID
func (_m *MockTodoService) GetGroupMembers(ctx context.Context, groupID uint, requesterID uint) ([]models.GroupShare, error) {
	ret := _m.Called(ctx, groupID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupMembers")
	}

	var r0 []models.GroupShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) ([]models.GroupShare, error)); ok {
		return rf(ctx, groupID, requesterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) []models.GroupShare); ok {
		r0 = rf(ctx, groupID, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, groupID, requesterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_GetGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupMembers'
type MockTodoService_GetGroupMembers_Call struct {
	*mock.Call
}

// GetGroupMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - requesterID uint
func (_e *MockTodoService_Expecter) GetGroupMembers(ctx interface{}, groupID interface{}, requesterID interface{}) *MockTodoService_GetGroupMembers_Call {
	return &MockTodoService_GetGroupMembers_Call{Call: _e.mock.On("GetGroupMembers", ctx, groupID, requesterID)}
}

func (_c *MockTodoService_GetGroupMembers_Call) Run(run func(ctx context.Context, groupID uint, requesterID uint)) *MockTodoService_GetGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_GetGroupMembers_Call) Return(_a0 []models.GroupShare, _a1 error) *MockTodoService_GetGroupMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_GetGroupMembers_Call) RunAndReturn(run func(context.Context, uint, uint) ([]models.GroupShare, error)) *MockTodoService_GetGroupMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroups provides a mock function with given fields: ctx, userID, search, status, sortParam, page, limit
func (_m *MockTodoService) GetGroups(ctx context.Context, userID uint, search string, status string, sortParam string, page int, limit int) ([]models.Todo, *dto.PaginationMeta, error) {
	ret := _m.Called(ctx, userID, search, status, sortParam, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []models.Todo
	var r1 *dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, int, int) ([]models.Todo, *dto.PaginationMeta, error)); ok {
		return rf(ctx, userID, search, status, sortParam, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, int, int) []models.Todo); ok {
		r0 = rf(ctx, userID, search, status, sortParam, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, string, string, int, int) *dto.PaginationMeta); ok {
		r1 = rf(ctx, userID, search, status, sortParam, page, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, string, string, string, int, int) error); ok {
		r2 = rf(ctx, userID, search, status, sortParam, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTodoService_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockTodoService_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - search string
//   - status string
//   - sortParam string
//   - page int
//   - limit int
func (_e *MockTodoService_Expecter) GetGroups(ctx interface{}, userID interface{}, search interface{}, status interface{}, sortParam interface{}, page interface{}, limit interface{}) *MockTodoService_GetGroups_Call {
	return &MockTodoService_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx, userID, search, status, sortParam, page, limit)}
}

func (_c *MockTodoService_GetGroups_Call) Run(run func(ctx context.Context, userID uint, search string, status string, sortParam string, page int, limit int)) *MockTodoService_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *MockTodoService_GetGroups_Call) Return(_a0 []models.Todo, _a1 *dto.PaginationMeta, _a2 error) *MockTodoService_GetGroups_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTodoService_GetGroups_Call) RunAndReturn(run func(context.Context, uint, string, string, string, int, int) ([]models.Todo, *dto.PaginationMeta, error)) *MockTodoService_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermission provides a mock function with given fields: ctx, entityID, userID
func (_m *MockTodoService) GetPermission(ctx context.Context, entityID uint, userID uint) (string, error) {
	ret := _m.Called(ctx, entityID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermission")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (string, error)); ok {
		return rf(ctx, entityID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) string); ok {
		r0 = rf(ctx, entityID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, entityID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_GetPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermission'
type MockTodoService_GetPermission_Call struct {
	*mock.Call
}

// GetPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID uint
//   - userID uint
func (_e *MockTodoService_Expecter) GetPermission(ctx interface{}, entityID interface{}, userID interface{}) *MockTodoService_GetPermission_Call {
	return &MockTodoService_GetPermission_Call{Call: _e.mock.On("GetPermission", ctx, entityID, userID)}
}

func (_c *MockTodoService_GetPermission_Call) Run(run func(ctx context.Context, entityID uint, userID uint)) *MockTodoService_GetPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_GetPermission_Call) Return(_a0 string, _a1 error) *MockTodoService_GetPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_GetPermission_Call) RunAndReturn(run func(context.Context, uint, uint) (string, error)) *MockTodoService_GetPermission_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedGroups provides a mock function with given fields: ctx, userID, search, status, sortParam, page, limit
func (_m *MockTodoService) GetSharedGroups(ctx context.Context, userID uint, search string, status string, sortParam string, page int, limit int) ([]models.GroupShare, *dto.PaginationMeta, error) {
	ret := _m.Called(ctx, userID, search, status, sortParam, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedGroups")
	}

	var r0 []models.GroupShare
	var r1 *dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, int, int) ([]models.GroupShare, *dto.PaginationMeta, error)); ok {
		return rf(ctx, userID, search, status, sortParam, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, int, int) []models.GroupShare); ok {
		r0 = rf(ctx, userID, search, status, sortParam, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, string, string, int, int) *dto.PaginationMeta); ok {
		r1 = rf(ctx, userID, search, status, sortParam, page, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, string, string, string, int, int) error); ok {
		r2 = rf(ctx, userID, search, status, sortParam, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTodoService_GetSharedGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedGroups'
type MockTodoService_GetSharedGroups_Call struct {
	*mock.Call
}

// GetSharedGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - search string
//   - status string
//   - sortParam string
//   - page int
//   - limit int
func (_e *MockTodoService_Expecter) GetSharedGroups(ctx interface{}, userID interface{}, search interface{}, status interface{}, sortParam interface{}, page interface{}, limit interface{}) *MockTodoService_GetSharedGroups_Call {
	return &MockTodoService_GetSharedGroups_Call{Call: _e.mock.On("GetSharedGroups", ctx, userID, search, status, sortParam, page, limit)}
}

func (_c *MockTodoService_GetSharedGroups_Call) Run(run func(ctx context.Context, userID uint, search string, status string, sortParam string, page int, limit int)) *MockTodoService_GetSharedGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *MockTodoService_GetSharedGroups_Call) Return(_a0 []models.GroupShare, _a1 *dto.PaginationMeta, _a2 error) *MockTodoService_GetSharedGroups_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTodoService_GetSharedGroups_Call) RunAndReturn(run func(context.Context, uint, string, string, string, int, int) ([]models.GroupShare, *dto.PaginationMeta, error)) *MockTodoService_GetSharedGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtasks provides a mock function with given fields: ctx, groupID, userID, page, limit
func (_m *MockTodoService) GetSubtasks(ctx context.Context, groupID uint, userID uint, page int, limit int) ([]models.Todo, *dto.PaginationMeta, error) {
	ret := _m.Called(ctx, groupID, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtasks")
	}

	var r0 []models.Todo
	var r1 *dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, int, int) ([]models.Todo, *dto.PaginationMeta, error)); ok {
		return rf(ctx, groupID, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, int, int) []models.Todo); ok {
		r0 = rf(ctx, groupID, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, int, int) *dto.PaginationMeta); ok {
		r1 = rf(ctx, groupID, userID, page, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, uint, int, int) error); ok {
		r2 = rf(ctx, groupID, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTodoService_GetSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtasks'
type MockTodoService_GetSubtasks_Call struct {
	*mock.Call
}

// GetSubtasks is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - userID uint
//   - page int
//   - limit int
func (_e *MockTodoService_Expecter) GetSubtasks(ctx interface{}, groupID interface{}, userID interface{}, page interface{}, limit interface{}) *MockTodoService_GetSubtasks_Call {
	return &MockTodoService_GetSubtasks_Call{Call: _e.mock.On("GetSubtasks", ctx, groupID, userID, page, limit)}
}

func (_c *MockTodoService_GetSubtasks_Call) Run(run func(ctx context.Context, groupID uint, userID uint, page int, limit int)) *MockTodoService_GetSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockTodoService_GetSubtasks_Call) Return(_a0 []models.Todo, _a1 *dto.PaginationMeta, _a2 error) *MockTodoService_GetSubtasks_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTodoService_GetSubtasks_Call) RunAndReturn(run func(context.Context, uint, uint, int, int) ([]models.Todo, *dto.PaginationMeta, error)) *MockTodoService_GetSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveShare provides a mock function with given fields: ctx, groupID, ownerID, sharedWithUserID
func (_m *MockTodoService) RemoveShare(ctx context.Context, groupID uint, ownerID uint, sharedWithUserID uint) error {
	ret := _m.Called(ctx, groupID, ownerID, sharedWithUserID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint) error); ok {
		r0 = rf(ctx, groupID, ownerID, sharedWithUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoService_RemoveShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveShare'
type MockTodoService_RemoveShare_Call struct {
	*mock.Call
}

// RemoveShare is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - ownerID uint
//   - sharedWithUserID uint
func (_e *MockTodoService_Expecter) RemoveShare(ctx interface{}, groupID interface{}, ownerID interface{}, sharedWithUserID interface{}) *MockTodoService_RemoveShare_Call {
	return &MockTodoService_RemoveShare_Call{Call: _e.mock.On("RemoveShare", ctx, groupID, ownerID, sharedWithUserID)}
}

func (_c *MockTodoService_RemoveShare_Call) Run(run func(ctx context.Context, groupID uint, ownerID uint, sharedWithUserID uint)) *MockTodoService_RemoveShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(uint))
	})
	return _c
}

func (_c *MockTodoService_RemoveShare_Call) Return(_a0 error) *MockTodoService_RemoveShare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoService_RemoveShare_Call) RunAndReturn(run func(context.Context, uint, uint, uint) error) *MockTodoService_RemoveShare_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, query, excludeUserID
func (_m *MockTodoService) SearchUsers(ctx context.Context, query string, excludeUserID uint) ([]models.User, error) {
	ret := _m.Called(ctx, query, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) ([]models.User, error)); ok {
		return rf(ctx, query, excludeUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) []models.User); ok {
		r0 = rf(ctx, query, excludeUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, query, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockTodoService_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - excludeUserID uint
func (_e *MockTodoService_Expecter) SearchUsers(ctx interface{}, query interface{}, excludeUserID interface{}) *MockTodoService_SearchUsers_Call {
	return &MockTodoService_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, excludeUserID)}
}

func (_c *MockTodoService_SearchUsers_Call) Run(run func(ctx context.Context, query string, excludeUserID uint)) *MockTodoService_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_SearchUsers_Call) Return(_a0 []models.User, _a1 error) *MockTodoService_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_SearchUsers_Call) RunAndReturn(run func(context.Context, string, uint) ([]models.User, error)) *MockTodoService_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ShareGroup provides a mock function with given fields: ctx, groupID, ownerID, req
func (_m *MockTodoService) ShareGroup(ctx context.Context, groupID uint, ownerID uint, req dto.ShareGroupRequest) (*models.GroupShare, error) {
	ret := _m.Called(ctx, groupID, ownerID, req)

	if len(ret) == 0 {
		panic("no return value specified for ShareGroup")
	}

	var r0 *models.GroupShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, dto.ShareGroupRequest) (*models.GroupShare, error)); ok {
		return rf(ctx, groupID, ownerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, dto.ShareGroupRequest) *models.GroupShare); ok {
		r0 = rf(ctx, groupID, ownerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GroupShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, dto.ShareGroupRequest) error); ok {
		r1 = rf(ctx, groupID, ownerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_ShareGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareGroup'
type MockTodoService_ShareGroup_Call struct {
	*mock.Call
}

// ShareGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - ownerID uint
//   - req dto.ShareGroupRequest
func (_e *MockTodoService_Expecter) ShareGroup(ctx interface{}, groupID interface{}, ownerID interface{}, req interface{}) *MockTodoService_ShareGroup_Call {
	return &MockTodoService_ShareGroup_Call{Call: _e.mock.On("ShareGroup", ctx, groupID, ownerID, req)}
}

func (_c *MockTodoService_ShareGroup_Call) Run(run func(ctx context.Context, groupID uint, ownerID uint, req dto.ShareGroupRequest)) *MockTodoService_ShareGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(dto.ShareGroupRequest))
	})
	return _c
}

func (_c *MockTodoService_ShareGroup_Call) Return(_a0 *models.GroupShare, _a1 error) *MockTodoService_ShareGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_ShareGroup_Call) RunAndReturn(run func(context.Context, uint, uint, dto.ShareGroupRequest) (*models.GroupShare, error)) *MockTodoService_ShareGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleCompleteSubtask provides a mock function with given fields: ctx, id, userID
func (_m *MockTodoService) ToggleCompleteSubtask(ctx context.Context, id uint, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleCompleteSubtask")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*models.Todo, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *models.Todo); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_ToggleCompleteSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleCompleteSubtask'
type MockTodoService_ToggleCompleteSubtask_Call struct {
	*mock.Call
}

// ToggleCompleteSubtask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - userID uint
func (_e *MockTodoService_Expecter) ToggleCompleteSubtask(ctx interface{}, id interface{}, userID interface{}) *MockTodoService_ToggleCompleteSubtask_Call {
	return &MockTodoService_ToggleCompleteSubtask_Call{Call: _e.mock.On("ToggleCompleteSubtask", ctx, id, userID)}
}

func (_c *MockTodoService_ToggleCompleteSubtask_Call) Run(run func(ctx context.Context, id uint, userID uint)) *MockTodoService_ToggleCompleteSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockTodoService_ToggleCompleteSubtask_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoService_ToggleCompleteSubtask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_ToggleCompleteSubtask_Call) RunAndReturn(run func(context.Context, uint, uint) (*models.Todo, error)) *MockTodoService_ToggleCompleteSubtask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function with given fields: ctx, id, req, userID
func (_m *MockTodoService) UpdateGroup(ctx context.Context, id uint, req dto.UpdateGroupRequest, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, id, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateGroupRequest, uint) (*models.Todo, error)); ok {
		return rf(ctx, id, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateGroupRequest, uint) *models.Todo); ok {
		r0 = rf(ctx, id, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, dto.UpdateGroupRequest, uint) error); ok {
		r1 = rf(ctx, id, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockTodoService_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req dto.UpdateGroupRequest
//   - userID uint
func (_e *MockTodoService_Expecter) UpdateGroup(ctx interface{}, id interface{}, req interface{}, userID interface{}) *MockTodoService_UpdateGroup_Call {
	return &MockTodoService_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, id, req, userID)}
}

func (_c *MockTodoService_UpdateGroup_Call) Run(run func(ctx context.Context, id uint, req dto.UpdateGroupRequest, userID uint)) *MockTodoService_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(dto.UpdateGroupRequest), args[3].(uint))
	})
	return _c
}

func (_c *MockTodoService_UpdateGroup_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoService_UpdateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_UpdateGroup_Call) RunAndReturn(run func(context.Context, uint, dto.UpdateGroupRequest, uint) (*models.Todo, error)) *MockTodoService_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSharePermission provides a mock function with given fields: ctx, groupID, ownerID, sharedWithUserID, req
func (_m *MockTodoService) UpdateSharePermission(ctx context.Context, groupID uint, ownerID uint, sharedWithUserID uint, req dto.UpdateShareRoleRequest) error {
	ret := _m.Called(ctx, groupID, ownerID, sharedWithUserID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSharePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, uint, dto.UpdateShareRoleRequest) error); ok {
		r0 = rf(ctx, groupID, ownerID, sharedWithUserID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTodoService_UpdateSharePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSharePermission'
type MockTodoService_UpdateSharePermission_Call struct {
	*mock.Call
}

// UpdateSharePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uint
//   - ownerID uint
//   - sharedWithUserID uint
//   - req dto.UpdateShareRoleRequest
func (_e *MockTodoService_Expecter) UpdateSharePermission(ctx interface{}, groupID interface{}, ownerID interface{}, sharedWithUserID interface{}, req interface{}) *MockTodoService_UpdateSharePermission_Call {
	return &MockTodoService_UpdateSharePermission_Call{Call: _e.mock.On("UpdateSharePermission", ctx, groupID, ownerID, sharedWithUserID, req)}
}

func (_c *MockTodoService_UpdateSharePermission_Call) Run(run func(ctx context.Context, groupID uint, ownerID uint, sharedWithUserID uint, req dto.UpdateShareRoleRequest)) *MockTodoService_UpdateSharePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(uint), args[4].(dto.UpdateShareRoleRequest))
	})
	return _c
}

func (_c *MockTodoService_UpdateSharePermission_Call) Return(_a0 error) *MockTodoService_UpdateSharePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTodoService_UpdateSharePermission_Call) RunAndReturn(run func(context.Context, uint, uint, uint, dto.UpdateShareRoleRequest) error) *MockTodoService_UpdateSharePermission_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubtask provides a mock function with given fields: ctx, id, req, userID
func (_m *MockTodoService) UpdateSubtask(ctx context.Context, id uint, req dto.UpdateSubtaskRequest, userID uint) (*models.Todo, error) {
	ret := _m.Called(ctx, id, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubtask")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateSubtaskRequest, uint) (*models.Todo, error)); ok {
		return rf(ctx, id, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateSubtaskRequest, uint) *models.Todo); ok {
		r0 = rf(ctx, id, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, dto.UpdateSubtaskRequest, uint) error); ok {
		r1 = rf(ctx, id, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTodoService_UpdateSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubtask'
type MockTodoService_UpdateSubtask_Call struct {
	*mock.Call
}

// UpdateSubtask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req dto.UpdateSubtaskRequest
//   - userID uint
func (_e *MockTodoService_Expecter) UpdateSubtask(ctx interface{}, id interface{}, req interface{}, userID interface{}) *MockTodoService_UpdateSubtask_Call {
	return &MockTodoService_UpdateSubtask_Call{Call: _e.mock.On("UpdateSubtask", ctx, id, req, userID)}
}

func (_c *MockTodoService_UpdateSubtask_Call) Run(run func(ctx context.Context, id uint, req dto.UpdateSubtaskRequest, userID uint)) *MockTodoService_UpdateSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(dto.UpdateSubtaskRequest), args[3].(uint))
	})
	return _c
}

func (_c *MockTodoService_UpdateSubtask_Call) Return(_a0 *models.Todo, _a1 error) *MockTodoService_UpdateSubtask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTodoService_UpdateSubtask_Call) RunAndReturn(run func(context.Context, uint, dto.UpdateSubtaskRequest, uint) (*models.Todo, error)) *MockTodoService_UpdateSubtask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTodoService creates a new instance of MockTodoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoService {
	mock := &MockTodoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
