// Code generated by mockery v2.53.6. DO NOT EDIT.

package controllers

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockGroupController is an autogenerated mock type for the GroupController type
type MockGroupController struct {
	mock.Mock
}

type MockGroupController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupController) EXPECT() *MockGroupController_Expecter {
	return &MockGroupController_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function with given fields: c
func (_m *MockGroupController) CreateGroup(c *gin.Context) {
	_m.Called(c)
}

// MockGroupController_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockGroupController_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockGroupController_Expecter) CreateGroup(c interface{}) *MockGroupController_CreateGroup_Call {
	return &MockGroupController_CreateGroup_Call{Call: _e.mock.On("CreateGroup", c)}
}

func (_c *MockGroupController_CreateGroup_Call) Run(run func(c *gin.Context)) *MockGroupController_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockGroupController_CreateGroup_Call) Return() *MockGroupController_CreateGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGroupController_CreateGroup_Call) RunAndReturn(run func(*gin.Context)) *MockGroupController_CreateGroup_Call {
	_c.Run(run)
	return _c
}

// DeleteGroup provides a mock function with given fields: c
func (_m *MockGroupController) DeleteGroup(c *gin.Context) {
	_m.Called(c)
}

// MockGroupController_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockGroupController_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockGroupController_Expecter) DeleteGroup(c interface{}) *MockGroupController_DeleteGroup_Call {
	return &MockGroupController_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", c)}
}

func (_c *MockGroupController_DeleteGroup_Call) Run(run func(c *gin.Context)) *MockGroupController_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockGroupController_DeleteGroup_Call) Return() *MockGroupController_DeleteGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGroupController_DeleteGroup_Call) RunAndReturn(run func(*gin.Context)) *MockGroupController_DeleteGroup_Call {
	_c.Run(run)
	return _c
}

// GetGroupByID provides a mock function with given fields: c
func (_m *MockGroupController) GetGroupByID(c *gin.Context) {
	_m.Called(c)
}

// MockGroupController_GetGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByID'
type MockGroupController_GetGroupByID_Call struct {
	*mock.Call
}

// GetGroupByID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockGroupController_Expecter) GetGroupByID(c interface{}) *MockGroupController_GetGroupByID_Call {
	return &MockGroupController_GetGroupByID_Call{Call: _e.mock.On("GetGroupByID", c)}
}

func (_c *MockGroupController_GetGroupByID_Call) Run(run func(c *gin.Context)) *MockGroupController_GetGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockGroupController_GetGroupByID_Call) Return() *MockGroupController_GetGroupByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGroupController_GetGroupByID_Call) RunAndReturn(run func(*gin.Context)) *MockGroupController_GetGroupByID_Call {
	_c.Run(run)
	return _c
}

// GetGroups provides a mock function with given fields: c
func (_m *MockGroupController) GetGroups(c *gin.Context) {
	_m.Called(c)
}

// MockGroupController_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockGroupController_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockGroupController_Expecter) GetGroups(c interface{}) *MockGroupController_GetGroups_Call {
	return &MockGroupController_GetGroups_Call{Call: _e.mock.On("GetGroups", c)}
}

func (_c *MockGroupController_GetGroups_Call) Run(run func(c *gin.Context)) *MockGroupController_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockGroupController_GetGroups_Call) Return() *MockGroupController_GetGroups_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGroupController_GetGroups_Call) RunAndReturn(run func(*gin.Context)) *MockGroupController_GetGroups_Call {
	_c.Run(run)
	return _c
}

// UpdateGroup provides a mock function with given fields: c
func (_m *MockGroupController) UpdateGroup(c *gin.Context) {
	_m.Called(c)
}

// MockGroupController_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockGroupController_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockGroupController_Expecter) UpdateGroup(c interface{}) *MockGroupController_UpdateGroup_Call {
	return &MockGroupController_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", c)}
}

func (_c *MockGroupController_UpdateGroup_Call) Run(run func(c *gin.Context)) *MockGroupController_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockGroupController_UpdateGroup_Call) Return() *MockGroupController_UpdateGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGroupController_UpdateGroup_Call) RunAndReturn(run func(*gin.Context)) *MockGroupController_UpdateGroup_Call {
	_c.Run(run)
	return _c
}

// NewMockGroupController creates a new instance of MockGroupController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupController {
	mock := &MockGroupController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
