// Code generated by mockery v2.53.6. DO NOT EDIT.

package controllers

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockShareController is an autogenerated mock type for the ShareController type
type MockShareController struct {
	mock.Mock
}

type MockShareController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShareController) EXPECT() *MockShareController_Expecter {
	return &MockShareController_Expecter{mock: &_m.Mock}
}

// GetGroupMembers provides a mock function with given fields: c
func (_m *MockShareController) GetGroupMembers(c *gin.Context) {
	_m.Called(c)
}

// MockShareController_GetGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupMembers'
type MockShareController_GetGroupMembers_Call struct {
	*mock.Call
}

// GetGroupMembers is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockShareController_Expecter) GetGroupMembers(c interface{}) *MockShareController_GetGroupMembers_Call {
	return &MockShareController_GetGroupMembers_Call{Call: _e.mock.On("GetGroupMembers", c)}
}

func (_c *MockShareController_GetGroupMembers_Call) Run(run func(c *gin.Context)) *MockShareController_GetGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockShareController_GetGroupMembers_Call) Return() *MockShareController_GetGroupMembers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShareController_GetGroupMembers_Call) RunAndReturn(run func(*gin.Context)) *MockShareController_GetGroupMembers_Call {
	_c.Run(run)
	return _c
}

// GetSharedGroups provides a mock function with given fields: c
func (_m *MockShareController) GetSharedGroups(c *gin.Context) {
	_m.Called(c)
}

// MockShareController_GetSharedGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedGroups'
type MockShareController_GetSharedGroups_Call struct {
	*mock.Call
}

// GetSharedGroups is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockShareController_Expecter) GetSharedGroups(c interface{}) *MockShareController_GetSharedGroups_Call {
	return &MockShareController_GetSharedGroups_Call{Call: _e.mock.On("GetSharedGroups", c)}
}

func (_c *MockShareController_GetSharedGroups_Call) Run(run func(c *gin.Context)) *MockShareController_GetSharedGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockShareController_GetSharedGroups_Call) Return() *MockShareController_GetSharedGroups_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShareController_GetSharedGroups_Call) RunAndReturn(run func(*gin.Context)) *MockShareController_GetSharedGroups_Call {
	_c.Run(run)
	return _c
}

// RemoveShare provides a mock function with given fields: c
func (_m *MockShareController) RemoveShare(c *gin.Context) {
	_m.Called(c)
}

// MockShareController_RemoveShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveShare'
type MockShareController_RemoveShare_Call struct {
	*mock.Call
}

// RemoveShare is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockShareController_Expecter) RemoveShare(c interface{}) *MockShareController_RemoveShare_Call {
	return &MockShareController_RemoveShare_Call{Call: _e.mock.On("RemoveShare", c)}
}

func (_c *MockShareController_RemoveShare_Call) Run(run func(c *gin.Context)) *MockShareController_RemoveShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockShareController_RemoveShare_Call) Return() *MockShareController_RemoveShare_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShareController_RemoveShare_Call) RunAndReturn(run func(*gin.Context)) *MockShareController_RemoveShare_Call {
	_c.Run(run)
	return _c
}

// SearchUsers provides a mock function with given fields: c
func (_m *MockShareController) SearchUsers(c *gin.Context) {
	_m.Called(c)
}

// MockShareController_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockShareController_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockShareController_Expecter) SearchUsers(c interface{}) *MockShareController_SearchUsers_Call {
	return &MockShareController_SearchUsers_Call{Call: _e.mock.On("SearchUsers", c)}
}

func (_c *MockShareController_SearchUsers_Call) Run(run func(c *gin.Context)) *MockShareController_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockShareController_SearchUsers_Call) Return() *MockShareController_SearchUsers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShareController_SearchUsers_Call) RunAndReturn(run func(*gin.Context)) *MockShareController_SearchUsers_Call {
	_c.Run(run)
	return _c
}

// ShareGroup provides a mock function with given fields: c
func (_m *MockShareController) ShareGroup(c *gin.Context) {
	_m.Called(c)
}

// MockShareController_ShareGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareGroup'
type MockShareController_ShareGroup_Call struct {
	*mock.Call
}

// ShareGroup is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockShareController_Expecter) ShareGroup(c interface{}) *MockShareController_ShareGroup_Call {
	return &MockShareController_ShareGroup_Call{Call: _e.mock.On("ShareGroup", c)}
}

func (_c *MockShareController_ShareGroup_Call) Run(run func(c *gin.Context)) *MockShareController_ShareGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockShareController_ShareGroup_Call) Return() *MockShareController_ShareGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShareController_ShareGroup_Call) RunAndReturn(run func(*gin.Context)) *MockShareController_ShareGroup_Call {
	_c.Run(run)
	return _c
}

// UpdateSharePermission provides a mock function with given fields: c
func (_m *MockShareController) UpdateSharePermission(c *gin.Context) {
	_m.Called(c)
}

// MockShareController_UpdateSharePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSharePermission'
type MockShareController_UpdateSharePermission_Call struct {
	*mock.Call
}

// UpdateSharePermission is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockShareController_Expecter) UpdateSharePermission(c interface{}) *MockShareController_UpdateSharePermission_Call {
	return &MockShareController_UpdateSharePermission_Call{Call: _e.mock.On("UpdateSharePermission", c)}
}

func (_c *MockShareController_UpdateSharePermission_Call) Run(run func(c *gin.Context)) *MockShareController_UpdateSharePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockShareController_UpdateSharePermission_Call) Return() *MockShareController_UpdateSharePermission_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShareController_UpdateSharePermission_Call) RunAndReturn(run func(*gin.Context)) *MockShareController_UpdateSharePermission_Call {
	_c.Run(run)
	return _c
}

// NewMockShareController creates a new instance of MockShareController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShareController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShareController {
	mock := &MockShareController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
