// Code generated by mockery v2.53.6. DO NOT EDIT.

package controllers

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockSubtaskController is an autogenerated mock type for the SubtaskController type
type MockSubtaskController struct {
	mock.Mock
}

type MockSubtaskController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubtaskController) EXPECT() *MockSubtaskController_Expecter {
	return &MockSubtaskController_Expecter{mock: &_m.Mock}
}

// CreateSubtask provides a mock function with given fields: c
func (_m *MockSubtaskController) CreateSubtask(c *gin.Context) {
	_m.Called(c)
}

// MockSubtaskController_CreateSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubtask'
type MockSubtaskController_CreateSubtask_Call struct {
	*mock.Call
}

// CreateSubtask is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSubtaskController_Expecter) CreateSubtask(c interface{}) *MockSubtaskController_CreateSubtask_Call {
	return &MockSubtaskController_CreateSubtask_Call{Call: _e.mock.On("CreateSubtask", c)}
}

func (_c *MockSubtaskController_CreateSubtask_Call) Run(run func(c *gin.Context)) *MockSubtaskController_CreateSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSubtaskController_CreateSubtask_Call) Return() *MockSubtaskController_CreateSubtask_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubtaskController_CreateSubtask_Call) RunAndReturn(run func(*gin.Context)) *MockSubtaskController_CreateSubtask_Call {
	_c.Run(run)
	return _c
}

// DeleteSubtask provides a mock function with given fields: c
func (_m *MockSubtaskController) DeleteSubtask(c *gin.Context) {
	_m.Called(c)
}

// MockSubtaskController_DeleteSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubtask'
type MockSubtaskController_DeleteSubtask_Call struct {
	*mock.Call
}

// DeleteSubtask is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSubtaskController_Expecter) DeleteSubtask(c interface{}) *MockSubtaskController_DeleteSubtask_Call {
	return &MockSubtaskController_DeleteSubtask_Call{Call: _e.mock.On("DeleteSubtask", c)}
}

func (_c *MockSubtaskController_DeleteSubtask_Call) Run(run func(c *gin.Context)) *MockSubtaskController_DeleteSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSubtaskController_DeleteSubtask_Call) Return() *MockSubtaskController_DeleteSubtask_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubtaskController_DeleteSubtask_Call) RunAndReturn(run func(*gin.Context)) *MockSubtaskController_DeleteSubtask_Call {
	_c.Run(run)
	return _c
}

// GetSubtasks provides a mock function with given fields: c
func (_m *MockSubtaskController) GetSubtasks(c *gin.Context) {
	_m.Called(c)
}

// MockSubtaskController_GetSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtasks'
type MockSubtaskController_GetSubtasks_Call struct {
	*mock.Call
}

// GetSubtasks is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSubtaskController_Expecter) GetSubtasks(c interface{}) *MockSubtaskController_GetSubtasks_Call {
	return &MockSubtaskController_GetSubtasks_Call{Call: _e.mock.On("GetSubtasks", c)}
}

func (_c *MockSubtaskController_GetSubtasks_Call) Run(run func(c *gin.Context)) *MockSubtaskController_GetSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSubtaskController_GetSubtasks_Call) Return() *MockSubtaskController_GetSubtasks_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubtaskController_GetSubtasks_Call) RunAndReturn(run func(*gin.Context)) *MockSubtaskController_GetSubtasks_Call {
	_c.Run(run)
	return _c
}

// ToggleCompleteSubtask provides a mock function with given fields: c
func (_m *MockSubtaskController) ToggleCompleteSubtask(c *gin.Context) {
	_m.Called(c)
}

// MockSubtaskController_ToggleCompleteSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleCompleteSubtask'
type MockSubtaskController_ToggleCompleteSubtask_Call struct {
	*mock.Call
}

// ToggleCompleteSubtask is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSubtaskController_Expecter) ToggleCompleteSubtask(c interface{}) *MockSubtaskController_ToggleCompleteSubtask_Call {
	return &MockSubtaskController_ToggleCompleteSubtask_Call{Call: _e.mock.On("ToggleCompleteSubtask", c)}
}

func (_c *MockSubtaskController_ToggleCompleteSubtask_Call) Run(run func(c *gin.Context)) *MockSubtaskController_ToggleCompleteSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSubtaskController_ToggleCompleteSubtask_Call) Return() *MockSubtaskController_ToggleCompleteSubtask_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubtaskController_ToggleCompleteSubtask_Call) RunAndReturn(run func(*gin.Context)) *MockSubtaskController_ToggleCompleteSubtask_Call {
	_c.Run(run)
	return _c
}

// UpdateSubtask provides a mock function with given fields: c
func (_m *MockSubtaskController) UpdateSubtask(c *gin.Context) {
	_m.Called(c)
}

// MockSubtaskController_UpdateSubtask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubtask'
type MockSubtaskController_UpdateSubtask_Call struct {
	*mock.Call
}

// UpdateSubtask is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSubtaskController_Expecter) UpdateSubtask(c interface{}) *MockSubtaskController_UpdateSubtask_Call {
	return &MockSubtaskController_UpdateSubtask_Call{Call: _e.mock.On("UpdateSubtask", c)}
}

func (_c *MockSubtaskController_UpdateSubtask_Call) Run(run func(c *gin.Context)) *MockSubtaskController_UpdateSubtask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSubtaskController_UpdateSubtask_Call) Return() *MockSubtaskController_UpdateSubtask_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubtaskController_UpdateSubtask_Call) RunAndReturn(run func(*gin.Context)) *MockSubtaskController_UpdateSubtask_Call {
	_c.Run(run)
	return _c
}

// NewMockSubtaskController creates a new instance of MockSubtaskController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubtaskController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubtaskController {
	mock := &MockSubtaskController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
