// Code generated by mockery v2.53.6. DO NOT EDIT.

package controllers

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthController is an autogenerated mock type for the AuthController type
type MockAuthController struct {
	mock.Mock
}

type MockAuthController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthController) EXPECT() *MockAuthController_Expecter {
	return &MockAuthController_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: c
func (_m *MockAuthController) Login(c *gin.Context) {
	_m.Called(c)
}

// MockAuthController_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthController_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockAuthController_Expecter) Login(c interface{}) *MockAuthController_Login_Call {
	return &MockAuthController_Login_Call{Call: _e.mock.On("Login", c)}
}

func (_c *MockAuthController_Login_Call) Run(run func(c *gin.Context)) *MockAuthController_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockAuthController_Login_Call) Return() *MockAuthController_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthController_Login_Call) RunAndReturn(run func(*gin.Context)) *MockAuthController_Login_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function with given fields: c
func (_m *MockAuthController) Register(c *gin.Context) {
	_m.Called(c)
}

// MockAuthController_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthController_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockAuthController_Expecter) Register(c interface{}) *MockAuthController_Register_Call {
	return &MockAuthController_Register_Call{Call: _e.mock.On("Register", c)}
}

func (_c *MockAuthController_Register_Call) Run(run func(c *gin.Context)) *MockAuthController_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockAuthController_Register_Call) Return() *MockAuthController_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthController_Register_Call) RunAndReturn(run func(*gin.Context)) *MockAuthController_Register_Call {
	_c.Run(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: c
func (_m *MockAuthController) UpdatePassword(c *gin.Context) {
	_m.Called(c)
}

// MockAuthController_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockAuthController_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockAuthController_Expecter) UpdatePassword(c interface{}) *MockAuthController_UpdatePassword_Call {
	return &MockAuthController_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", c)}
}

func (_c *MockAuthController_UpdatePassword_Call) Run(run func(c *gin.Context)) *MockAuthController_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockAuthController_UpdatePassword_Call) Return() *MockAuthController_UpdatePassword_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthController_UpdatePassword_Call) RunAndReturn(run func(*gin.Context)) *MockAuthController_UpdatePassword_Call {
	_c.Run(run)
	return _c
}

// NewMockAuthController creates a new instance of MockAuthController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthController {
	mock := &MockAuthController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
