// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type GroupShare struct {
	ID               uint32
	GroupID          uint32
	OwnerID          uint32
	SharedWithUserID uint32
	Permission       string
	CreatedAt        time.Time
}

type Todo struct {
	ID           uint32
	Title        string
	Description  string
	Completed    bool
	DueDate      sql.NullTime
	UserID       uint32
	ParentTodoID sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID        uint32
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
}
