// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM group_shares WHERE group_id = ?
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID uint32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupShare = `-- name: CreateGroupShare :execresult

INSERT INTO group_shares (group_id, owner_id, shared_with_user_id, permission, created_at)
VALUES (?, ?, ?, ?, NOW())
`

type CreateGroupShareParams struct {
	GroupID          uint32
	OwnerID          uint32
	SharedWithUserID uint32
	Permission       string
}

// ============================================================
// Group Shares
// ============================================================
func (q *Queries) CreateGroupShare(ctx context.Context, arg CreateGroupShareParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGroupShare,
		arg.GroupID,
		arg.OwnerID,
		arg.SharedWithUserID,
		arg.Permission,
	)
}

const createTodo = `-- name: CreateTodo :execresult

INSERT INTO todos (title, description, completed, due_date, user_id, parent_todo_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateTodoParams struct {
	Title        string
	Description  string
	Completed    bool
	DueDate      sql.NullTime
	UserID       uint32
	ParentTodoID sql.NullInt32
}

// ============================================================
// Todos (Groups + Subtasks share this table)
// ============================================================
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
		arg.UserID,
		arg.ParentTodoID,
	)
}

const createUser = `-- name: CreateUser :execresult

INSERT INTO users (name, email, password, created_at)
VALUES (?, ?, ?, NOW())
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
}

// ============================================================
// Users
// ============================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email, arg.Password)
}

const deleteGroupShare = `-- name: DeleteGroupShare :exec
DELETE FROM group_shares
WHERE group_id = ? AND shared_with_user_id = ?
`

type DeleteGroupShareParams struct {
	GroupID          uint32
	SharedWithUserID uint32
}

func (q *Queries) DeleteGroupShare(ctx context.Context, arg DeleteGroupShareParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupShare, arg.GroupID, arg.SharedWithUserID)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, title, description, completed, due_date, user_id, parent_todo_id, created_at, updated_at
FROM todos
WHERE id = ?
  AND parent_todo_id IS NULL
LIMIT 1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uint32) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.DueDate,
		&i.UserID,
		&i.ParentTodoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupShare = `-- name: GetGroupShare :one
SELECT id, group_id, owner_id, shared_with_user_id, permission, created_at
FROM group_shares
WHERE group_id = ?
  AND shared_with_user_id = ?
LIMIT 1
`

type GetGroupShareParams struct {
	GroupID          uint32
	SharedWithUserID uint32
}

func (q *Queries) GetGroupShare(ctx context.Context, arg GetGroupShareParams) (GroupShare, error) {
	row := q.db.QueryRowContext(ctx, getGroupShare, arg.GroupID, arg.SharedWithUserID)
	var i GroupShare
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.OwnerID,
		&i.SharedWithUserID,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupSharesByGroupID = `-- name: GetGroupSharesByGroupID :many
SELECT
    gs.id, gs.group_id, gs.owner_id, gs.shared_with_user_id, gs.permission, gs.created_at,
    u.id   AS sw_id,
    u.name AS sw_name,
    u.email AS sw_email
FROM group_shares gs
JOIN users u ON u.id = gs.shared_with_user_id
WHERE gs.group_id = ?
`

type GetGroupSharesByGroupIDRow struct {
	ID               uint32
	GroupID          uint32
	OwnerID          uint32
	SharedWithUserID uint32
	Permission       string
	CreatedAt        time.Time
	SwID             uint32
	SwName           string
	SwEmail          string
}

func (q *Queries) GetGroupSharesByGroupID(ctx context.Context, groupID uint32) ([]GetGroupSharesByGroupIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupSharesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupSharesByGroupIDRow{}
	for rows.Next() {
		var i GetGroupSharesByGroupIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.OwnerID,
			&i.SharedWithUserID,
			&i.Permission,
			&i.CreatedAt,
			&i.SwID,
			&i.SwName,
			&i.SwEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByUserID = `-- name: GetGroupsByUserID :many
SELECT id, title, description, completed, due_date, user_id, parent_todo_id, created_at, updated_at
FROM todos
WHERE user_id = ?
  AND parent_todo_id IS NULL
  AND (? = '' OR title LIKE ? OR description LIKE ?)
ORDER BY created_at DESC
`

type GetGroupsByUserIDParams struct {
	UserID      uint32
	Column2     interface{}
	Title       string
	Description string
}

// Returns top-level groups (parent_todo_id IS NULL) for a user.
// Filtering by status/sort is done in Go after this query.
func (q *Queries) GetGroupsByUserID(ctx context.Context, arg GetGroupsByUserIDParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserID,
		arg.UserID,
		arg.Column2,
		arg.Title,
		arg.Description,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.DueDate,
			&i.UserID,
			&i.ParentTodoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharesByUserID = `-- name: GetSharesByUserID :many
SELECT
    gs.id, gs.group_id, gs.owner_id, gs.shared_with_user_id, gs.permission, gs.created_at,
    t.id AS g_id, t.title AS g_title, t.description AS g_description,
    t.completed AS g_completed, t.due_date AS g_due_date,
    t.user_id AS g_user_id, t.parent_todo_id AS g_parent_todo_id,
    t.created_at AS g_created_at, t.updated_at AS g_updated_at,
    u.id AS owner_id_val, u.name AS owner_name, u.email AS owner_email
FROM group_shares gs
JOIN todos t ON t.id = gs.group_id
LEFT JOIN todos sub ON sub.parent_todo_id = t.id
JOIN users u ON u.id = t.user_id
WHERE gs.shared_with_user_id = ?
GROUP BY gs.id, t.id, u.id
`

type GetSharesByUserIDRow struct {
	ID               uint32
	GroupID          uint32
	OwnerID          uint32
	SharedWithUserID uint32
	Permission       string
	CreatedAt        time.Time
	GID              uint32
	GTitle           string
	GDescription     string
	GCompleted       bool
	GDueDate         sql.NullTime
	GUserID          uint32
	GParentTodoID    sql.NullInt32
	GCreatedAt       time.Time
	GUpdatedAt       time.Time
	OwnerIDVal       uint32
	OwnerName        string
	OwnerEmail       string
}

func (q *Queries) GetSharesByUserID(ctx context.Context, sharedWithUserID uint32) ([]GetSharesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSharesByUserID, sharedWithUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharesByUserIDRow{}
	for rows.Next() {
		var i GetSharesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.OwnerID,
			&i.SharedWithUserID,
			&i.Permission,
			&i.CreatedAt,
			&i.GID,
			&i.GTitle,
			&i.GDescription,
			&i.GCompleted,
			&i.GDueDate,
			&i.GUserID,
			&i.GParentTodoID,
			&i.GCreatedAt,
			&i.GUpdatedAt,
			&i.OwnerIDVal,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtasksByParentAndUser = `-- name: GetSubtasksByParentAndUser :many
SELECT id, title, description, completed, due_date, user_id, parent_todo_id, created_at, updated_at
FROM todos
WHERE parent_todo_id = ?
  AND user_id = ?
ORDER BY created_at ASC
`

type GetSubtasksByParentAndUserParams struct {
	ParentTodoID sql.NullInt32
	UserID       uint32
}

func (q *Queries) GetSubtasksByParentAndUser(ctx context.Context, arg GetSubtasksByParentAndUserParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getSubtasksByParentAndUser, arg.ParentTodoID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.DueDate,
			&i.UserID,
			&i.ParentTodoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtasksByParentID = `-- name: GetSubtasksByParentID :many
SELECT id, title, description, completed, due_date, user_id, parent_todo_id, created_at, updated_at
FROM todos
WHERE parent_todo_id = ?
ORDER BY created_at ASC
`

func (q *Queries) GetSubtasksByParentID(ctx context.Context, parentTodoID sql.NullInt32) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getSubtasksByParentID, parentTodoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.DueDate,
			&i.UserID,
			&i.ParentTodoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, description, completed, due_date, user_id, parent_todo_id, created_at, updated_at
FROM todos
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTodoByID(ctx context.Context, id uint32) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.DueDate,
		&i.UserID,
		&i.ParentTodoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, created_at
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, created_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uint32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, password, created_at
FROM users
WHERE id != ?
  AND (name LIKE ? OR email LIKE ?)
LIMIT 20
`

type SearchUsersParams struct {
	ID    uint32
	Name  string
	Email string
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.ID, arg.Name, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupSharePermission = `-- name: UpdateGroupSharePermission :exec
UPDATE group_shares
SET permission = ?
WHERE group_id = ? AND shared_with_user_id = ?
`

type UpdateGroupSharePermissionParams struct {
	Permission       string
	GroupID          uint32
	SharedWithUserID uint32
}

func (q *Queries) UpdateGroupSharePermission(ctx context.Context, arg UpdateGroupSharePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupSharePermission, arg.Permission, arg.GroupID, arg.SharedWithUserID)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET title = ?, description = ?, completed = ?, due_date = ?, updated_at = NOW()
WHERE id = ?
`

type UpdateTodoParams struct {
	Title       string
	Description string
	Completed   bool
	DueDate     sql.NullTime
	ID          uint32
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password string
	ID       uint32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
