// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountGroupMembers(ctx context.Context, groupID uint32) (int64, error)
	// ============================================================
	// Group Shares
	// ============================================================
	CreateGroupShare(ctx context.Context, arg CreateGroupShareParams) (sql.Result, error)
	// ============================================================
	// Todos (Groups + Subtasks share this table)
	// ============================================================
	CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error)
	// ============================================================
	// Users
	// ============================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteGroupShare(ctx context.Context, arg DeleteGroupShareParams) error
	DeleteTodo(ctx context.Context, id uint32) error
	GetGroupByID(ctx context.Context, id uint32) (Todo, error)
	GetGroupShare(ctx context.Context, arg GetGroupShareParams) (GroupShare, error)
	GetGroupSharesByGroupID(ctx context.Context, groupID uint32) ([]GetGroupSharesByGroupIDRow, error)
	// Returns top-level groups (parent_todo_id IS NULL) for a user.
	// Filtering by status/sort is done in Go after this query.
	GetGroupsByUserID(ctx context.Context, arg GetGroupsByUserIDParams) ([]Todo, error)
	GetSharesByUserID(ctx context.Context, sharedWithUserID uint32) ([]GetSharesByUserIDRow, error)
	GetSubtasksByParentAndUser(ctx context.Context, arg GetSubtasksByParentAndUserParams) ([]Todo, error)
	GetSubtasksByParentID(ctx context.Context, parentTodoID sql.NullInt32) ([]Todo, error)
	GetTodoByID(ctx context.Context, id uint32) (Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint32) (User, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateGroupSharePermission(ctx context.Context, arg UpdateGroupSharePermissionParams) error
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
